wandb_version: 1

tex_size:
  desc: null
  value: 1024
mesh_inp_size:
  desc: null
  value: 21918
n_latent:
  desc: null
  value: 256
n_cams:
  desc: null
  value: 38
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725371149.571401
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
